# Homebrew formula for wisetree.
#
# This file is normally regenerated by cargo-dist on every tagged release
# and pushed to the `victorcorcos/homebrew-tap` repository. The version
# committed here is a template/baseline so the structure is reviewable
# without spelunking the tap repo. Update the SHAs/URL after each release
# (or let cargo-dist do it).

class Wisetree < Formula
  desc "Interactive CLI for creating and managing Git worktrees"
  homepage "https://github.com/victorcorcos/wisetree"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/victorcorcos/wisetree/releases/download/v1.0.0/wisetree-aarch64-apple-darwin.tar.xz"
      sha256 "REPLACE_WITH_RELEASE_SHA"
    end
    on_intel do
      url "https://github.com/victorcorcos/wisetree/releases/download/v1.0.0/wisetree-x86_64-apple-darwin.tar.xz"
      sha256 "REPLACE_WITH_RELEASE_SHA"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/victorcorcos/wisetree/releases/download/v1.0.0/wisetree-aarch64-unknown-linux-gnu.tar.xz"
      sha256 "REPLACE_WITH_RELEASE_SHA"
    end
    on_intel do
      url "https://github.com/victorcorcos/wisetree/releases/download/v1.0.0/wisetree-x86_64-unknown-linux-gnu.tar.xz"
      sha256 "REPLACE_WITH_RELEASE_SHA"
    end
  end

  def install
    bin.install "wisetree"
  end

  test do
    assert_match "Wisetree v#{version}", shell_output("#{bin}/wisetree --version")
  end
end
